version: '3'
services:
  web:
    restart: always
    build: ./avia_app
    ports:
     - "5000:5000"
    volumes:
     - .:/avia_app
    environment:
        FLASK_ENV: development
    depends_on:
     - redis
  redis:
    image: redis