version: '3'
services:
  web:
    restart: always
    build: avia_app
    ports:
     - "8080:5000"
    environment:
        FLASK_ENV: development
    depends_on:
     - redis
  redis:
    image: redis